version: "3.8"

x-search-cred: &search-creds
  PROJECT_CODE: ${PROJECT_CODE}


networks:
  default:
    name: search_system
    external: false

services:
  search_system:
    build:
      context: ..
      dockerfile: Dockerfile
    container_name: server-${PROJECT_CODE}
    environment:
      <<: *search-creds

  telegram_bot:
    build:
      context: ../bot
      dockerfile: Dockerfile
    container_name: telegram-${PROJECT_CODE}
    environment:
      <<: *search-creds

  postgres_db:
    image: postgres:13
    container_name: postgres-db
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_USER_PASS}
      POSTGRES_DB: ${PG_DATABASE_NAME}
      POSTGRES_MULTIPLE_DATABASES: ${PG_USER}:${PG_USER_PASS}
    volumes:
      - pg-db-volume:/var/lib/postgresql/data
      - ./create-multiple-db.sh:/docker-entrypoint-initdb.d/init-multi-postgres-databases.sh
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "${PG_USER}" ]
      interval: 5s
      retries: 5
    restart: always
    ports:
      - 5433:5432

volumes:
  elast-data:
  pg-db-volume: